
name: magellan_app
description: Magellan Restaurant App (single-restaurant)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg

dependencies:
  socket_io_client: ^2.0.3
